FROM python:3.13

WORKDIR /app

RUN apt-get update && apt-get install -y gcc python3-dev

COPY . .

RUN pip install --no-cache-dir asyncpg uvicorn fastapi

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]