FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip gcc python3-dev git curl wget vim

WORKDIR /app

COPY . .

RUN pip3 install asyncpg uvicorn fastapi --break-system-packages

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]